57883 Single Server docs for Innovation Installation
CortexIntelligentAutomation/docs_v2022 pull request #15
Opened 2022-07-18 14:33 UTC by cortex-le

2022-08-02 15:50 UTC, cortex-bw requested changes

2022-08-02 15:50 UTC, cortex-bw commented on content/en/docs/getting-started/on-premise/install-innovation-only/single-server-without-ha/install-web-application-server.md
> +5. Set the `Physical path` to `C:\inetpub\wwwroot\Cortex\Gateway` by clicking on the ellipses `…` and selecting the appropriate directory. Create the `C:\inetpub\wwwroot\Cortex\Gateway` directory if
Add step 6 to click OK

2022-08-02 15:50 UTC, cortex-bw commented on content/en/docs/getting-started/on-premise/install-innovation-only/single-server-without-ha/prerequisites.md
> +[^4]: SQL Server Express, Standard and Enterprise are supported. Other databases are not supported.
add comment that TDE is not supported for SQL Express

2022-08-03 08:21 UTC, cortex-le commented on content/en/docs/getting-started/on-premise/install-innovation-only/single-server-without-ha/install-web-application-server.md
> +5. Set the `Physical path` to `C:\inetpub\wwwroot\Cortex\Gateway` by clicking on the ellipses `…` and selecting the appropriate directory. Create the `C:\inetpub\wwwroot\Cortex\Gateway` directory if
Added click ok

2022-08-04 14:19 UTC, merged